# Generated by Django 3.2.16 on 2024-02-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_historicalorganizationcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verticals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Vertical',
                'verbose_name_plural': 'Verticals',
            },
        ),
        migrations.CreateModel(
            name='OrganizationVerticals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_id', to='organizations.organization')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vertical_id', to='org_customizations.verticals')),
            ],
            options={
                'verbose_name': 'Organization Vertical',
                'verbose_name_plural': 'Organizations Verticals',
            },
        ),
    ]
