# Generated by Django 3.2.16 on 2024-02-18 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_historicalorganizationcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verticals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Vertical',
                'verbose_name_plural': 'Verticals',
            },
        ),
        migrations.CreateModel(
            name='OrganizationExtraData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heb_name', models.CharField(max_length=255, unique=True, verbose_name='heb_name')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_extra_data_id', to='organizations.organization')),
                ('vertical', models.ManyToManyField(related_name='vertical_id', to='org_customizations.Verticals')),
            ],
            options={
                'verbose_name': 'Custom Organization',
                'verbose_name_plural': 'Custom Organizations',
            },
        ),
    ]
