# Generated by Django 3.2.16 on 2024-02-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_historicalorganizationcourse'),
        ('org_customizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationverticals',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_vertical_id', to='organizations.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationExtraData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heb_name', models.CharField(max_length=255, unique=True, verbose_name='heb_name')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_extra_data_id', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Custom Organization',
                'verbose_name_plural': 'Custom Organizations',
            },
        ),
    ]
