# Generated by Django 3.2.16 on 2024-03-11 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_customizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationextradata',
            name='api_user',
            field=models.ManyToManyField(null=True, related_name='permission_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
