# Generated by Django 3.2.16 on 2023-11-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_overviews', '0032_delete_campusilreportablecoursesdigital'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusilReportableCoursesDigital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isReportable', models.BooleanField(default=False)),
                ('course_overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_overviews.courseoverview')),
            ],
        ),
    ]
