# Generated by Django 3.2.16 on 2023-12-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0032_delete_campusilreportablecoursesdigital'),
        ('digital_gov_reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusilDigitalHubOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_mail', models.JSONField(blank=True, default=list)),
                ('course_overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_overviews.courseoverview')),
            ],
        ),
    ]
