# Generated by Django 3.2.16 on 2023-12-06 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_historicalorganizationcourse'),
        ('course_overviews', '0032_delete_campusilreportablecoursesdigital'),
        ('digital_gov_reports', '0002_campusildigitalhuborganization'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusilDigitalHubOrganizationCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_overviews.courseoverview')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization Course',
                'verbose_name_plural': 'Organization Courses',
            },
        ),
        migrations.CreateModel(
            name='CampusilDigitalHubOrganizationEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_mail', models.JSONField(blank=True, default=list)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization Email',
                'verbose_name_plural': 'Organization Email',
            },
        ),
        migrations.DeleteModel(
            name='CampusilDigitalHubOrganization',
        ),
    ]
