# Generated by Django 3.2.16 on 2023-12-06 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_historicalorganizationcourse'),
        ('course_overviews', '0032_delete_campusilreportablecoursesdigital'),
        ('digital_gov_reports', '0003_auto_20231206_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusilOrganizationCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='course_overviews.courseoverview')),
            ],
            options={
                'verbose_name': 'Organization Course',
                'verbose_name_plural': 'Organization Courses',
            },
        ),
        migrations.CreateModel(
            name='CampusilOrganizationExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_column='org_email', max_length=255)),
                ('org_id', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization Extension',
                'verbose_name_plural': 'Organizations Extension',
            },
        ),
        migrations.RemoveField(
            model_name='campusildigitalhuborganizationemails',
            name='org_id',
        ),
        migrations.DeleteModel(
            name='CampusilDigitalHubOrganizationCourses',
        ),
        migrations.DeleteModel(
            name='CampusilDigitalHubOrganizationEmails',
        ),
        migrations.AddField(
            model_name='campusilorganizationcourses',
            name='digital_hub_org_id',
            field=models.ForeignKey(db_column='dh_org_id', on_delete=django.db.models.deletion.CASCADE, to='digital_gov_reports.campusilorganizationextension'),
        ),
    ]
