# Generated by Django 3.2.16 on 2024-02-18 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_overviews', '0026_courseoverview_entrance_exam'),
        ('ccx_customizations', '0004_alter_customcourseforedxextradata_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOverviewExtraData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id', to='course_overviews.courseoverview')),
                ('origin', models.ManyToManyField(related_name='origin_id', to='ccx_customizations.Origin')),
            ],
            options={
                'verbose_name': 'Custom Course Overview',
                'verbose_name_plural': 'Custom Course Overviews',
            },
        ),
    ]
