# Generated by Django 3.2.16 on 2024-02-05 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ccx_customizations', '0004_alter_customcourseforedxextradata_year'),
        ('course_overviews', '0026_courseoverview_entrance_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOverview_Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_id', to='course_overviews.courseoverview')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_id', to='ccx_customizations.origin')),
            ],
            options={
                'verbose_name': 'Course Overviews Origin',
                'verbose_name_plural': 'Course Overviews Origins',
            },
        ),
    ]
