# Generated by Django 3.2.16 on 2023-11-09 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0031_campusilreportablecoursesdigital'),
        ('campus_edx_extensions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusilReportableCoursesDigital',
            fields=[
                ('courseoverview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course_overviews.courseoverview')),
                ('isReportable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('course_overviews.courseoverview',),
        ),
    ]
