# Generated by Django 3.2.16 on 2023-12-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_date_signals', '0001_initial'),
        ('entitlements', '0015_add_unique_together_constraint'),
        ('course_home_api', '0001_initial'),
        ('course_duration_limits', '0008_auto_20190313_1634'),
        ('course_modes', '0013_auto_20200115_2022'),
        ('discussions', '0010_auto_20220203_2134'),
        ('discounts', '0002_auto_20191022_1720'),
        ('student', '0044_courseenrollmentcelebration_celebrate_weekly_goal'),
        ('course_overviews', '0032_delete_campusilreportablecoursesdigital'),
        ('content_type_gating', '0008_auto_20190313_1634'),
        ('digital_gov_reports', '0001_initial'),
        ('campus_edx_extensions', '0002_campusilreportablecoursesdigital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampusilReportableCoursesDigital',
        ),
    ]
