# Generated by Django 3.2.16 on 2023-11-28 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ccx', '0007_customcourseforedx_coach2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomCourseForEdXExtraData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=255)),
                ('class_num', models.IntegerField()),
                ('organization', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('ccx_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ccx_extra_data', to='ccx.customcourseforedx')),
                ('ccx_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ccx_extra_data_origin', to='ccx_customizations.origin')),
            ],
        ),
    ]
