# Generated by Django 3.2.16 on 2023-11-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccx_customizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
