# Generated by Django 3.2.16 on 2023-11-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccx_customizations', '0003_auto_20231128_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcourseforedxextradata',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
